// swift-tools-version:5.9
//
// IshEmbed — Swift Package wrapping iSH (arm64 emulator + syscall layer +
// fakefs) as an embeddable Linux runtime for iOS host apps.
//
// Two pieces of artifact distribution:
//
//  1. The Swift sources in Sources/IshEmbed are built by SwiftPM as
//     usual.
//  2. The native iSH kernel + embed glue is shipped as a prebuilt
//     `libIshKernel.xcframework`, attached to a GitHub Release. The
//     binaryTarget below points at that release so consumers don't need
//     Meson, Ninja, llvm or zig — they just `Add Package Dependency`.
//
// To build the xcframework yourself (for development against this repo
// directly), run:
//
//     git submodule update --init
//     PATH="/opt/homebrew/opt/llvm/bin:/opt/homebrew/opt/lld/bin:$PATH" \
//         scripts/build-ios.sh
//
// then change the `IshKernel` target below to a `.binaryTarget(path:)`.
// `scripts/build-rootfs.sh` is only needed for local host integration tests;
// its output is not part of the XCFramework or a distributable package.
// Nested iSH submodules are not inputs to this package build.

import PackageDescription

let package = Package(
    name: "IshEmbed",
    platforms: [
        .iOS("18.0"),
    ],
    products: [
        .library(name: "IshEmbed", targets: ["IshEmbed"]),
    ],
    targets: [
        // System module exposing the C ABI to Swift via modulemap.
        .target(
            name: "CIshEmbed",
            path: "Sources/CIshEmbed",
            publicHeadersPath: "include",
            cSettings: [
                .headerSearchPath("include"),
            ]
        ),
        // Prebuilt iSH kernel + embed glue. Updated when a new release is
        // tagged; checksum is regenerated by scripts/release.sh.
        .binaryTarget(
            name: "IshKernel",
            url: "https://github.com/jacklv-coder/ish-arm64-pkg/releases/download/v0.4.0-abi.13/libIshKernel.xcframework.zip",
            checksum: "4ce31bf518437d333a856fd02d04094f9399a35f0d2c24139fa21bfb2e4c49bc"
        ),
        // High-level Swift API.
        .target(
            name: "IshEmbed",
            dependencies: [
                "CIshEmbed",
                "IshKernel",
            ],
            path: "Sources/IshEmbed",
            linkerSettings: [
                // libsqlite3 is the only iSH dependency that isn't already
                // statically linked into libIshKernel.a.
                .linkedLibrary("sqlite3"),
            ]
        ),
        .testTarget(
            name: "IshEmbedTests",
            dependencies: ["IshEmbed"],
            path: "Tests/IshEmbedTests"
        ),
    ]
)
