#!/usr/bin/env python3
"""Generate a deterministic C translation unit for the bundled supervisor."""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path


SYMBOL = "ish_embed_bundled_supervisor"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    return parser.parse_args()


def format_bytes(data: bytes) -> str:
    rows = []
    for offset in range(0, len(data), 12):
        chunk = data[offset : offset + 12]
        rows.append("    " + ", ".join(f"0x{byte:02x}" for byte in chunk) + ",")
    return "\n".join(rows)


def main() -> int:
    args = parse_args()
    data = args.input.read_bytes()
    if not data:
        raise SystemExit("supervisor binary is empty")

    digest = hashlib.sha256(data).hexdigest()
    guest_path = f"/sbin/.ishsv-ishembed-sha256-{digest}"
    source = f"""/* Generated by scripts/generate-supervisor-blob.py. */
#include <stddef.h>
#include <stdint.h>

#if defined(__GNUC__)
#define ISH_BLOB_HIDDEN __attribute__((used, visibility(\"hidden\")))
#else
#define ISH_BLOB_HIDDEN
#endif

ISH_BLOB_HIDDEN const uint8_t {SYMBOL}[] = {{
{format_bytes(data)}
}};
ISH_BLOB_HIDDEN const size_t {SYMBOL}_len = sizeof({SYMBOL});
ISH_BLOB_HIDDEN const char {SYMBOL}_sha256[] = "{digest}";
ISH_BLOB_HIDDEN const char {SYMBOL}_guest_path[] = "{guest_path}";
"""
    args.output.parent.mkdir(parents=True, exist_ok=True)
    with args.output.open("w", encoding="utf-8", newline="\n") as output:
        output.write(source)
    print(f"{digest}  {args.input}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
